### ISSUE TITLE
Some questions about spherical transform

### ISSUE THREAD

**Issue by TimLeeCV** [chi-kaichen/S2-ShadowNet#1]
Dear Kaichen Chi,

I am very interested in your work, particularly the spherical transform mentioned in your paper. However, I have encountered some difficulties while attempting to replicate this part of the study. Therefore, I would like to inquire about specific details of the paper.

Could you please provide more information  on the implementation of the spherical transform? Any additional resources or clarifications would be greatly appreciated.

Thank you for your time and assistance.

Best regards！

**Comment by chi-kaichen** [comment]
Thank you for your attention! Currently, this manuscript has not been accepted, so I haven't made the code public yet. I suggest you refer to https://github.com/XJTU-XGU/RSDA, especially the links therein. It will be of great help to you.

Best regards！
